### PR TITLE
Added my Web Projects 

### PR DESCRIPTION
**Pull request by anubhav201241**
Issue no: #11 

Description:

Added My Web Project in the repository

### CODE REVIEW

**Comment by BonkReaction** [comment]
Hey @anubhav201241, can you check your project structure?
Yours: image
Basically put your code part in code folder, add a thumbnail of your project and add the deployment txt file in which the deployed link of your project will be there.
Correct: 
image

**Comment by lostgirljourney** [comment]
Hey @anubhav201241, can you check your project structure?
Yours: image
Basically, put your code part in the code folder, add a thumbnail of your project and add the deployment text file in which the deployed link of your project will be there.
Correct: 
image

**Comment by anubhav201241** [comment]
Hey, Thank you for pointing this out I have made the changes, Do Let me know if any other changes are required!

**Comment by lostgirljourney** [comment]
image
@anubhav201241 check the extension of text file 😅

**Review by DevrajDC — APPROVED** [review]
Looks good to me, merging it!

**Pull request merged**
