### PR TITLE
Want to add my demo portfolio project to the repository

### PR DESCRIPTION
**Pull request by Rosy03**
Hello Design and Code Community. 
I hereby have made a demo portfolio project which I have worked hard and want to showcase on this repository. I am participating in "Hackoctober fest 2021". Hence sorry for the haste.
Kindly review and accept this PR. 
@DevrajDC and @lostgirljourney and @OctoplusNinja I hope you will accept this and also add the necessary tags related to "Hackoctober fest 2021".
Thank you.

### CODE REVIEW

**Review by lostgirljourney — CHANGES_REQUESTED** [review]
image

change the folder name from **Code** to **code**.

**Comment by OctoplusNinja** [comment]
@Rosy03, remove the first blank line from deploymentLink.txt.
image

**Comment by Rosy03** [comment]
> @Rosy03, remove the first blank line from deploymentLink.txt. image

Done. Please Accept now.

**Comment by Rosy03** [comment]
> image
> 
> change the folder name from **Code** to **code**.

Done. Please accept now.

**Pull request merged**
