### PR TITLE
Added a Chrome Extension

### PR DESCRIPTION
**Pull request by imsushant12**
Hi team,
I made a Chrome Extension using HTML, CSS and JavaScript. It is deployed on Chrome Webstore : (https://chrome.google.com/webstore/detail/the-one-tap/hieblegcgoipinfbledfdfgadnokjdge/related?hl=en&authuser=0). Please add it in your code base.

### CODE REVIEW

**Comment by OctoplusNinja** [comment]
Is it possible to decrese the height of thumbnail.png a bit? @imsushant12

**Comment by imsushant12** [comment]
> Is it possible to decrese the height of thumbnail.png a bit? @imsushant12

They I would have to crop the image into half. Will it be okay?

**Comment by OctoplusNinja** [comment]
> > Is it possible to decrese the height of thumbnail.png a bit? @imsushant12
> 
> Then I would have to crop the image into half. Will it be okay?
yes, I think it'll be good, and if not, let me know, I'll merge the PR.

**Comment by imsushant12** [comment]
> > > Is it possible to decrese the height of thumbnail.png a bit? @imsushant12
> > 
> > 
> > Then I would have to crop the image into half. Will it be okay?
> 
> yes, I think it'll be good, and if not, let me know, I'll merge the PR.

I am cropping the image, please let me know if it is okay or not.

**Comment by OctoplusNinja** [comment]
Merging @imsushant12 🚀.

**Pull request merged**
