### PR TITLE
adding projects

### PR DESCRIPTION
**Pull request by AaquibAli**
added Projects followed with guidelines

### CODE REVIEW

**Comment by lostgirljourney** [comment]
Hey @AaquibAli, follow the folder structure.
After your name, it should have a folder with the name of your Project and then code files.
```
root
└──  public
|      └──Projects
|          ├── Your Name
|          │    ├── Project Name
|          │    │     └── Code files
|          |    │     └── deployedLink.txt
|          |    |     └── thumbnail.png
|          |    |
|          │    │
|          │    └── Project Name
|          │          └── Code files
|          |          └── deployedLink.txt
|          |          └── thumbnail.png
|          |        
|          |
|          └── Your Name
|               ├── Project Name    
|               │     └── Code files
|               │     └── deployedLink.txt
|               |     └── thumbnail.png
|               |
|               │   
|               └── Project Name
|                     └── Code files
|                     └── deployedLink.txt
|                     └── thumbnail.png
|           
└──  pages
└──  styles          
└──  README.MD
```

**Comment by DevrajDC** [comment]
There is some merge conflicts, so kindly check it again.

**Comment by AaquibAli** [comment]
ok

**Comment by DevrajDC** [comment]
Closing this PR since its not updated.

**Comment by AaquibAli** [comment]
Bhai mai update kr rha hu
Wait kro

**Comment by AaquibAli** [comment]
adding contents which required

**Pull request merged**
