### PR TITLE
Added SigUp Page UI

### PR DESCRIPTION
**Pull request by dipakpatil025**
I add signup page temple
th

### CODE REVIEW

**Comment by dipakpatil025** [comment]
whats the issue all the checks are failed ?

**Comment by lostgirljourney** [comment]
image

@dipakpatil025 put your code and all files inside a folder named `Project Name` where "Project Name" is the name of your project.

Correct: 
image

**Comment by lostgirljourney** [comment]
@dipakpatil025 follow this <https://github.com/Design-and-Code/Projects-showcase/blob/main/CONTIBUTING.md>

**Comment by lostgirljourney** [comment]
@dipakpatil025 closing PR.

**Pull request closed without merging**
